"""Add notification_enabled, theme to User; add LoginActivity table

Revision ID: eb34073b9099
Revises: 0f8259d1ecb7
Create Date: 2025-05-24 16:59:13.902048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb34073b9099'
down_revision = '0f8259d1ecb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')
        batch_op.drop_column('notification_enabled')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))

    op.drop_table('login_activity')
    # ### end Alembic commands ###
